server:
  port: 2550

spring:
  application:
    name: catalog
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
  sql:
    init:
      mode: always #utilizzo di schema.sql per inizializzare il db
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true #utilizzo di schema.sql per inizializzare il db

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "catalog"
    description: "Catalog microservice"
    version: "1.0.0"