server:
  port: 2550

spring:
  application:
    name: customers
  config:
    import: optional:configserver
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://customers-db:5432/customers
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "customers"
    description: "Customers microservice"
    version: "1.0.0"