server:
  port: 2550

spring:
  application:
    name: customers
  config:
    import: optional:configserver
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://orders-db:5432/orders
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true